### ISSUE TITLE
Bottom section of the UI not visible and inability to make UI window smaller

### ISSUE THREAD

**Issue by prnvrna** [AkashaProject/Community#120]
#### System information

AKASHA version: '0.6.1 '

Operating System: ' Ubuntu 17.10'

#### Expected behaviour
The UI should either be responsive if the window is not re-sizable. The below buttons should be visible while syncing.

#### Actual behaviour
There is no way to see the below buttons, no resize is possible. So practically, I am not able to see any buttons while installing as well as after install. I am attaching a screenshot, you can see my profile image below is not completely visible.
![screenshot from 2018-01-18 14-45-07](https://user-images.githubusercontent.com/1384615/35089908-38aa41a6-fc5e-11e7-9cc0-231137b8fdf8.png)

#### Steps to reproduce the problem
Install app on Ubuntu 17.10 using snap and simply run the application. Following are my display settings:
![screenshot from 2018-01-18 14-41-22](https://user-images.githubusercontent.com/1384615/35089757-e41983e0-fc5d-11e7-84d2-5be2ed2d4daa.png)

**Comment by SeverS** [comment]
Hi,
On the same topic: #130 
Let's move the conversation there!

Thanks!
