### ISSUE TITLE
[0.6.1] Add notification bubble for cycled AETH

### ISSUE THREAD

**Issue by karalabe** [AkashaProject/Community#123]
When cycling AETH, it would be nice to have a notification bubble that the AETH is ready to be collected. I completely forgot that I was cycling and was surprised that "oh look, 50 AETH".

Perhaps the same way that you have the blue dot on the tx audit log, you could have it on the AETH balance.

![aeth](https://i.imgur.com/QNIcfvN.png)

**Comment by quininez** [comment]
done
