### ISSUE TITLE
Karma level 0: says that I can publish entries, but I can't

### ISSUE THREAD

**Issue by jamesray1** [AkashaProject/Community#131]
#### System information

AKASHA version: `0.6.1`

Operating System: `Ubuntu 17.10`

#### Expected behaviour
It's hard to know, there may be a contradiction. Can I only create posts if I have a higher karma level, or should I be able to create posts?

#### Actual behaviour
I created a draft, filled in the title and body, couldn't create a tag with the error that I don't have enough karma, then couldn't find anywhere to actually publish my draft.

**Comment by bogdanbrezuica** [comment]
@jamesray1 have you tried to publish using existing tags? if you don't have enough Karma, you can't create new tags, but you should be able to post entries using existing tags

**Comment by jamesray1** [comment]
Yeah I thought that I tried to publish using #akasha, but I got the error. Now when I try again, it works!

**Comment by jamesray1** [comment]
So after adding tags I still can't see how to publish the draft.

**Comment by jamesray1** [comment]
Hi, I just tried to use beta.akasha.world and was able to publish a post. It might have something to do with that earlier I may not have got ETH from the faucet, or as suggested above I tried to create a tag that didn't exist without enough karma.
