### ISSUE TITLE
Redundant and malleable data field in comments

### ISSUE THREAD

**Issue by karalabe** [AkashaProject/Community#152]
Comment IPFS objects have a `date` field in them:

```json
{
   "content":"{\"entityMap\":{\"0\":{\"type\":\"emoji\",\"mutability\":\"IMMUTABLE\",\"data\":{\"emojiUnicode\":\"🙌\"}}},\"blocks\":[{\"key\":\"ffslq\",\"text\":\"Massive 🙌 \",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[{\"offset\":8,\"length\":1,\"key\":0}],\"data\":{}}]}",
   "date":"2018-01-13T11:27:37.138Z"
}
```

I don't see the purpose of the `date` field however.

In order to retrieve the IPFS hash of an Akasha comment, I currently need to look up the `Comments.Publish` event from the blockchain. If I have the log, I have the block hash too in which it was included, and as such I can look up the publication time from there. As such, the `date` field in a comment IPFS object feels redundant.

Worse however, I as the poster can put whatever date I want in the comment, so I may put a "past" date in and fake Akasha into thinking the comment was made in the past (or future for the fun of it).

What was the design goal with putting the date in there?

**Comment by karalabe** [comment]
Also, what's with the `json in string in json`? Why not just have `content` a json tree?

**Comment by kenshyx** [comment]
The `date` field is not used for displaying publish date for a comment(we're using the `publishDate` provided by contract `Comments` method `getComment`). Its only functionality is to force to calculate a new ipfs hash on the client.

**Comment by kenshyx** [comment]
Regarding the stringified json for content, ipfs objects have a max size so when that occurs the content is split in multiple ipfs objects.
