### ISSUE TITLE
Please Help - Akasha Beta - Synchronization was stopped

### ISSUE THREAD

**Issue by forgeeffect** [AkashaProject/Community#154]
#### System information

AKASHA version: `Beta`

Operating System: `Windows`

#### Expected behaviour
Sync goes through

#### Actual behaviour
Sync never takes off
Geth doesn't go through?
No sure really*

#### Steps to reproduce the problem
I have no clue
When I click "Details" it says stuff like:

INFO
00:23:41
cpu:geth:stdout: Executing (\\INSPIRON-M5010\ROOT\CIMV2:Win32_Process.Handle="9204")->setpriority()

 Method execution successful.

 Out Parameters:
 instance of __PARAMETERS
 {
 ReturnValue = 0;
 };

INFO
00:23:41
cpu:geth:stderr: 

ERROR
00:23:41
geth: exited with code: 1

ERROR
00:23:41
geth: exited with code: 1

INFO
00:23:37
cpu:geth:stderr: 

INFO
00:23:37
cpu:geth:stdout: Executing (\\INSPIRON-M5010\ROOT\CIMV2:Win32_Process.Handle="9204")->setpriority()

 Method execution successful.

 Out Parameters:
 instance of __PARAMETERS
 {
 ReturnValue = 0;
 };

INFO
00:23:36
geth:spawn:close: 1

ERROR
00:23:36
geth: exited with code: 1

INFO
00:22:50
cpu:geth:stderr: 

INFO
00:22:50
cpu:geth:stdout: Executing (\\INSPIRON-M5010\ROOT\CIMV2:Win32_Process.Handle="9204")->setpriority()

 Method execution successful.

 Out Parameters:
 instance of __PARAMETERS
 {
 ReturnValue = 0;
 };

INFO
00:22:50
geth:spawn:close: 1

ERROR
00:22:50
geth: exited with code: 1

ERROR
00:22:12
geth: exited with code: 1

ERROR
00:21:29
geth: exited with code: 1

ERROR
00:28:42
geth: exited with code: 1

ERROR
00:28:08
geth: exited with code: 1

ERROR
00:28:08
geth: exited with code: 1

**Comment by SeverS** [comment]
Hello,
This might be related to #161 . Do you still have this issue?

Thanks!
SeverS
