### ISSUE TITLE
Fails to start ipfs service

### ISSUE THREAD

**Issue by littleboy0k** [AkashaProject/Community#160]
#### Expected behavior
The program should start the ipfs service normally without any problems.

#### Actual behavior
The program fails to start ipfs service.

#### How to reproduce

1. Download and start akasha. 
2. Wait for it to sync with the testnet.
3. After the sync is complete, it will show a "Next" button.
4. Clicking on the button doesn't do anything. It is expected to start the ipfs service.

* Browser: Google Chrome 61.0.3163.91 (Official Build) (64-bit)
* Operating system: Windows
* JavaScript: V8 6.1.534.37
* User Agent:	Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.91 Safari/537.36

#### Recording Of The Bug

![11. Akasha can't start ipfs service 21.01.2018.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1516513192/gzvhrfsy7yshwv0xrtbh.gif)

    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@littleboy/fails-to-start-ipfs-service">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by SeverS** [comment]
Hello,

Do you still have this issue?
If no, can you remember how did you solved it? 😸 

Thanks for reporting!
