### ISSUE TITLE
Uploading pictures

### ISSUE THREAD

**Issue by etzm** [AkashaProject/Community#168]
#### System information

AKASHA version: Version 0.6.0 (0.6.0)
& Version 0.6.1 (0.6.1)
Operating System: OSX Sierra 10.12.6 

#### Expected behaviour
After uploading an image it should be visible in a post.

#### Actual behaviour
Images seem to upload, but are not shown. 

#### Steps to reproduce the problem
Create a new entry and upload a .png from your computer. 

Issue persists on the new version.

**Comment by SeverS** [comment]
Hi, @etzm,

Can you please provide me the image to test it? Thanks!

**Comment by etzm** [comment]
Hi!
I attached 2 png screenshots of the kindI tried uploading. 
Possibly the problem has been resolved in the meantime? 
Best. 

Martin

**Comment by SeverS** [comment]
Hello,

This issue was addressed in the last release.
If you still have troubles, feel free to re-open this

Thanks,
SeverS
