### ISSUE TITLE
Error occurred to run the system 

### ISSUE THREAD

**Issue by as50as** [AkashaProject/Community#171]
#### System information

AKASHA version: ` `AKASHA-0.6.1-win.zip

Operating System: ` `Win 10

#### Steps to reproduce the problem
net::ERR_NETWORK_ACCESS_DENIED
[0;37m13:51:42.842 [31mERROR [0;34m floodsub: [0merror reading rpc from <peer.ID U1EVSo>: connection reset [0;37mcomm.go:36[0m

[0;37m13:39:20.614 [31mERROR [0;34m floodsub: [0merror reading rpc from <peer.ID SoLSaf>: connection reset [0;37mcomm.go:36[0m [0;37m13:39:20.614 [31mERROR [0;34m floodsub: [0merror reading rpc from <peer.ID SoLV4B>: connection reset [0;37mcomm.go:36[0m [0;37m13:39:20.614 [31mERROR [0;34m floodsub: [0merror reading rpc from <peer.ID SoLPpp>: connection reset [0;37mcomm.go:36[0m [0;37m13:39:20.614 [31mERROR [0;34m floodsub: [0merror reading rpc from <peer.ID ZY7MtK>: connection reset [0;37mcomm.go:36[0m

**Comment by kenshyx** [comment]
`net::ERR_NETWORK_ACCESS_DENIED` You're using a proxy or firewall, also you should update to latest version to see if it fixes your issue.
