### ISSUE TITLE
Enhancements

### ISSUE THREAD

**Issue by SeverS** [AkashaProject/Community#175]
- [x] Tag-editor => autofocus and scroll into view when 2 lines tags
- [x] External link dialog => redesign and add "trust this domain checkbox"
- [x] User settings => view/remove trusted domains
- [x] Text editor => increase editor click surface and focus editor on click
- [x] Tags search/suggestions (main) => change stop chars
- [ ] Fullscreen image viewer => add "open original"
- [x] Entry page => entry versions dropdown arrow should not be visible if there is only 1 version

**Comment by starrychloe** [comment]
[] Right click menu for copy/cut/paste

**Comment by SeverS** [comment]
I will create a new issue with those unchecked marks
