### ISSUE TITLE
when enter the entries, show the error code EGFE01 

### ISSUE THREAD

**Issue by nicoholo** [AkashaProject/Community#180]
#### System information

AKASHA version: ` `
0.6.2
Operating System: ` `
OS
#### Expected behaviour
enter the entries

#### Actual behaviour
load the entries

#### Steps to reproduce the problem
enter entries
![wechatimg18](https://user-images.githubusercontent.com/36099217/35765558-2e606d9c-0901-11e8-861c-aaa42f6927a0.jpeg)

**Comment by SeverS** [comment]
This issue is no longer reproducible

Thank you for reporting!
