### ISSUE TITLE
update profile failed and check the history have the block confirmed.

### ISSUE THREAD

**Issue by nicoholo** [AkashaProject/Community#181]
#### System information

AKASHA version: ` `
0.6.2
Operating System: ` `
Mac
#### Expected behaviour
edit and update profile

#### Actual behaviour
update profile

#### Steps to reproduce the problem
update profile
<img width="1277" alt="2018-02-03 6 35 34" src="https://user-images.githubusercontent.com/36099217/35766331-1861bdb0-0911-11e8-8424-69926f477faa.png">

**Comment by sebastianrs95** [comment]
It took some time to update, but for me it did. Are you still having the same problem?

**Comment by nicoholo** [comment]
still not ok 
nothing to be changed.

**Comment by quininez** [comment]
Could not reproduce this issue, if you still have this problem please let us know.
