### ISSUE TITLE
Publishing link

### ISSUE THREAD

**Issue by itsdono** [AkashaProject/Community#201]
#### System information

AKASHA version: ` 0.6.2`

Operating System: `Windows 10`

#### Expected behaviour
Attempting to publish link

#### Actual behaviour
system hangs for a few minutes, then says "Error code DPE01
An error occured while publishing your draft"

Sometimes a post is published, other times I have to do the process multiple attempts.

Looks like the various attempts on Etherscan are showing as 'Unconfirmed.'

#### Steps to reproduce the problem
click to publish a link, enter article link and some text below (link: https://www.trustnodes.com/2018/02/10/coinbase-launches-paypal-like-plugging-ethereum-bitcoin-bitcoin-cash-litecoin)
![screen](https://user-images.githubusercontent.com/36351931/36069313-f4edd004-0e9b-11e8-8870-46be997c7aa6.png)

FYI, my profile is:  @itsdono

P.S. Looks like the system 'burped' the posts out, so perhaps they timed out stuck in a queue, waiting for a confirmation?

**Comment by SeverS** [comment]
Hello @itsdono !
Yes, probably the transaction took longer than usual. You should wait for the transaction confirmation (success or error). In the meantime you can leave that page and browse the app until the transaction gets mined.

Thanks for reporting!
Sever
