### ISSUE TITLE
Wrong error message: "only lowercase alphanumeric characters are allowed"

### ISSUE THREAD

**Issue by ligi** [AkashaProject/Community#206]
#### System information

AKASHA version: `0.6.2`

Operating System: ` Ubuntu 17.04`

#### Expected behaviour

Correct error message (I think the error message should be "username needs to be longer than 4 characters" - or even better allow username with length==4 - using ligi as username everywhere - would be sad if I have to use something else for akasha - not sure what the reasoning for this minimum is anyway)

#### Actual behaviour

![selection_214](https://user-images.githubusercontent.com/111600/36093606-745ff542-0feb-11e8-81a4-7663520a6222.png)

**Comment by kenshyx** [comment]
The min length for username is 2 atm. Which keyboard lang/layout do you use?

**Comment by ligi** [comment]
Great to hear that 2 is the minimum and I should be able to use ligi - was using the german keyboard layout - but there are no special characters from this layout in there

**Comment by kenshyx** [comment]
I checked your username now, it seems like its already registered O_o
