### ISSUE TITLE
IPSF not working

### ISSUE THREAD

**Issue by globalbiz21st** [AkashaProject/Community#212]
#### System information : Dell Inspiron 13, 2 in 1

AKASHA version: ` ` 0.6.2

Operating System: ` `Window 10

#### Actual behaviour : Error code IGPE01
An error occurred while getting IPFS service ports

#### Steps to reproduce the problem: dont know

**Comment by scriptin** [comment]
Check if you have something else running on those ports. If you click on the IPFS icon in the top right corner, you can see which ports it uses.

**Comment by globalbiz21st** [comment]
it worked , i changed the path and now its ok.
