### ISSUE TITLE
Invalid username validation

### ISSUE THREAD

**Issue by ligi** [AkashaProject/Community#215]
when going to edit user profile it tells me my username is already taken. I think it validates the same as for new accounts here - but should not be red and alarming that the username is taken by yourself already ;-)

![selection_232](https://user-images.githubusercontent.com/111600/36488128-fda55c50-1722-11e8-8f16-7854cb974b2d.png)

**Comment by kenshyx** [comment]
Yes, this is a known bug. Its fixed in the next release this week.

**Comment by ligi** [comment]
Oh - looking forward to this - would keep it open until the release so there is no other instance opened of this one. Did search for `username` and `validation` before - found nothing describing this problem - so opened this one.
