### ISSUE TITLE
Issue with installing and running the beta the first time

### ISSUE THREAD

**Issue by jamesray1** [AkashaProject/Community#219]
I previously installed and used the alpha.

```
james@james-Streacom:~% snap refresh akasha
snap "akasha" has no updates available
james@james-Streacom:~% akasha
zsh: command not found: akasha
james@james-Streacom:~% snap install akasha
snap "akasha" is already installed, see "snap refresh --help"
james@james-Streacom:~% akasha
zsh: command not found: akasha
```

Akasha isn't found when I search for it in the apps.

When I extracted the Zip file (other methods had issues) and opened the akasha exec file, Akasha opened, prompting me to sync, so I did, but 30 minutes later it is still syncing, and when I click on details, nothing happens. It also froze. I was also syncing Parity at the time.         

#### System information

AKASHA version: `0.6.2`

Operating System: Ubuntu 17.10, GNOME

**Comment by scriptin** [comment]
Does the first problem go away after you open a new terminal window? It seems like some scripts were simply not [`source`](https://ss64.com/bash/source.html)d properly. Running `source ~/.bash_profile` after `snap install akasha` may fix the problem. I just close and reopen a terminal is such cases.

**Comment by jamesray1** [comment]
@scriptin, in a new terminal window:

```
 james@james-Streacom  ~  snap install akasha
snap "akasha" is already installed, see "snap refresh --help"
 james@james-Streacom  ~  source ~/.bash_profile
 james@james-Streacom  ~  snap install akasha
snap "akasha" is already installed, see "snap refresh --help"
```

**Comment by jamesray1** [comment]
The version in the menu in Akasha is 0.6.2.

**Comment by jamesray1** [comment]
Now it is syncing. I don't have Parity running now. I guess that may have slown down Akasha to a halt, at least while I was looking at it.

**Comment by jamesray1** [comment]
But the icon for Akasha looks like this in the sidebar:
![screenshot from 2018-03-01 13-08-43](https://user-images.githubusercontent.com/16969914/36823525-b1b5226e-1d51-11e8-8a4e-7162b3617afe.png)

**Comment by jamesray1** [comment]
I can't log in with the previous identity that I made in the alpha.

**Comment by scriptin** [comment]
Try this: `echo $PATH | tr ":" "\n" | grep snap`

My result:

~~~
$ echo $PATH | tr ":" "\n" | grep snap
/snap/bin
~~~

If you don't see this line, it means that for some reason snaps are not on your path. You can add it manually.

As for your screenshot, I can see IPFS icon is red. Click on it and see what's in the log. Also, check if you have something else running on its ports.

**Comment by jamesray1** [comment]
I added snap to my path. I don't know how it was removed.

IPFS is green now.

**Comment by SeverS** [comment]
@jamesray1 
Do you managed to get it working?

I will close this issue for now but feel free to re-open it if necessary!

Thanks!
SeverS

**Comment by jamesray1** [comment]
This was for the program; I haven't used it on Manjaro yet, just the web version. But IIRC I was able to get it working at the time.
