### ISSUE TITLE
Request ETH/AETH web flow

### ISSUE THREAD

**Issue by MihaiAlisie** [AkashaProject/Community#225]
Seems like we missed this flow - after unlocking the metamask vault the user should have an easy way to:

- [ ] Request test ETH
- [ ] Request test AETH

On another note, clicking on the guest user icon in the lower left side and requesting test ETH in order to register profile does not seem to work.

**Comment by SeverS** [comment]
Hello!

I will close this for now since it it's outdated.

Thanks!
