### ISSUE TITLE
Akasha gives error when trying to get test ether

### ISSUE THREAD

**Issue by codename-littleboy** [AkashaProject/Community#226]
#### Expected behavior
Aksaha users should be able to get test ether so that they can create a new akasha account and use it.

#### Actual behavior
Akasha gives error when trying to get test ether.

#### How to reproduce
1, Open Akasha and wait for it to sync to the test network
2. Press create new identity
3. Give a passphrase and enter
4. Now in this step, akasha fails to give test eth for creating account

* Akasha Version: 0.6.2
* Operating system: Windows 10

#### Recording Of The Bug
![Akasha gives error when trying to get test ether.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1522028127/dudm8eajrxf4ibyoxo8h.gif)

    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@littleboy/akasha-gives-error-when-trying-to-get-test-ether">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by SeverS** [comment]
Hello!
This issue is solved!
Thanks for reporting!
SeverS
