### ISSUE TITLE
Not able to upvote

### ISSUE THREAD

**Issue by sebastianrs95** [AkashaProject/Community#228]
#### System information

AKASHA version: Web

Operating System: 

#### Expected behaviour
Click on upvote and see the vote.

#### Actual behaviour
Gives the following error:
"ocurred while upvoting ETH Balance Confussion"

#### Steps to reproduce the problem
Try to upvote a comment or a post.

**Comment by SeverS** [comment]
I think this is fixed now!
Feel free to re-open if it's the case

Thanks!
