### ISSUE TITLE
Wrong generation of links to entries

### ISSUE THREAD

**Issue by sebastianrs95** [AkashaProject/Community#229]
#### System information

AKASHA version: Web

Operating System: 

#### Expected behaviour
Generate a link to an entry for access within the web app.

#### Actual behaviour
Generates something like the next example:
akasha.network/#/0x29be5f8732ee2ff10a4069acce8040136a0d1881/0xf6c2e08a6d0bc8f6ccd2fcfb6c601bed3efb3e79056a58e75889475c8f816203

#### Steps to reproduce the problem
Select a post and click on share link.

**Comment by SeverS** [comment]
This is fixed now,
Thanks for reporting @sebastianrs95 😺
