### ISSUE TITLE
Can't get through initial install

### ISSUE THREAD

**Issue by ElecMonk** [AkashaProject/Community#230]
#### System information

AKASHA version: 0.6.2

Operating System: Win10

#### Expected behaviour
Beta Install completes

#### Actual behaviour
Doesn't complete. Stops about 99.99% and won't complete

#### Steps to reproduce the p
![capture](https://user-images.githubusercontent.com/38030438/38302986-c6d2fb82-3843-11e8-9526-d15175fe9c8c.PNG)
roblem

**Comment by SeverS** [comment]
Hello!

This may be related to #309. Let's move the conversation there!

Thanks!
SeverS
