### ISSUE TITLE
I can't sync.

### ISSUE THREAD

**Issue by Bazror** [AkashaProject/Community#231]
AKASHA version: `0.6.2`

Operating System: `Windows7-64bit `

Akasha Green. IPFS Green. Geth  Green. The antivirus is off. I did a clean install again, but no sync.
http://prntscr.com/j1c6ga
http://prntscr.com/j1c6rt
http://prntscr.com/j1c6z4
+
http://prntscr.com/j1c9v7 stuck here.
+ 
http://prntscr.com/j1caco more intel.

Please advise.

**Comment by SeverS** [comment]
Hey @Bazror 
Please try to re-sync your clock using 'internet time'.

Also related issues:
#309 #252 #75
