### ISSUE TITLE
48 Years ago

### ISSUE THREAD

**Issue by ligi** [AkashaProject/Community#234]
just trying out 0.7.0 and experienced this:

![selection_024](https://user-images.githubusercontent.com/111600/38943269-415e0dc2-4331-11e8-9a9a-5dac3b6f313c.png)

Either there was some time-travel involved or this is a bug

**Comment by kenshyx** [comment]
Nah just solidity `now`, it happens sometimes :D. We'll get rid of it when we update the contracts.
