### ISSUE TITLE
Just a question (sorry)

### ISSUE THREAD

**Issue by RainOfPain125** [AkashaProject/Community#240]
I did not notice anywhere I could ask questions, so I came here. Please recommend a place for future questions ;w;

I installed the program onto my computer assuming that all this 'cloud computing' meant using leftover CPU resources, but I've noticed that akasha is using my GPU a ton. Why would it do this? A typical server wouldn't have a consumer-grade GTX 1050, 1060, 1070, 1080, so on in it, so why would it use this in it's workloads?

Is there anyway to disable akasha from using my GPU? Because I have been using my GPU on the side for Crypto mining. Unless akasha is smart enough to stop using my GPU while I use it for other things, especially mining crypto while I'm asleep.

**Comment by kenshyx** [comment]
It shouldn't use GPU. If you still wan to use Akasha you can try the web version at https://beta.akasha.world
