### ISSUE TITLE
Error code GSE01 Geth service could not be started

### ISSUE THREAD

**Issue by dzhejs** [AkashaProject/Community#242]
#### System information

AKASHA version: `0.7.0-mac`

Operating System: `macOS 10.12.6 `

#### Happens both with normal and light sync. From log details:
ERROR
10:54:57
geth: exited with code: 1

ERROR
10:54:57
geth:sync:error: Fatal: Error starting protocol stack: datadir already used by another process

ERROR
10:54:54
geth: exited with code: 1

ERROR
10:54:54
geth:sync:error: Fatal: Error starting protocol stack: datadir already used by another process

ERROR
10:53:15
geth: exited with code: 1

ERROR
10:53:15
geth:sync:error: Fatal: Error starting protocol stack: datadir already used by another process

ERROR
10:52:50
geth: exited with code: 1

ERROR
10:52:50
geth:sync:error: Fatal: Error starting protocol stack: datadir already used by another process

ERROR
10:57:30
geth: exited with code: 1

INFO
10:57:30
Fatal: Error starting protocol stack: datadir already used by another process

ERROR
10:57:30
geth:sync:error: Fatal: Error starting protocol stack: datadir already used by another process

INFO
10:57:30
INFO [04-24|10:57:30] Maximum peer count ETH=25 LES=0 total=25

INFO
10:55:51
geth:spawn:close: 1

ERROR
10:55:51
geth: exited with code: 1

<img width="1276" alt="screen shot 2018-04-24 at 11 02 28" src="https://user-images.githubusercontent.com/33941331/39174087-56ff0014-47af-11e8-8b0b-cb450c85bad0.png">
<img width="1276" alt="screen shot 2018-04-24 at 11 02 28" src="https://user-images.githubusercontent.com/33941331/39174117-70931a4c-47af-11e8-9e42-936b3e9fc507.png">

**Comment by kenshyx** [comment]
You have two instances of geth running on the same configuration.
