### ISSUE TITLE
Syncying forever

### ISSUE THREAD

**Issue by AkashaTilo** [AkashaProject/Community#252]
#### System information

AKASHA version: ` 0.7.2`

Operating System: `macOS Sierra `

#### Steps to reproduce the problem
Download 0.7.2 (on my windows comp I had the same)

![screen shot 2018-04-29 at 21 46 01](https://user-images.githubusercontent.com/35579089/39413088-cbb47e48-4bfb-11e8-86de-2273643ee038.png)

**Comment by SeverS** [comment]
Hello!
Please see #309 

Thanks for reporting!
SeverS
