### ISSUE TITLE
Ah snap! Something went terribly wrong

### ISSUE THREAD

**Issue by ligi** [AkashaProject/Community#255]
#### System information

AKASHA version: `0.7.2`

Operating System: `Ubuntu 18.04 `

#### Expected behaviour

no crash

#### Actual behaviour

crash

#### Steps to reproduce the problem

sorry - but not sure what I did there :-( 
![selection_044](https://user-images.githubusercontent.com/111600/39630594-0f854884-4fb0-11e8-8f78-3619c2b5ff09.png)

TypeError: Cannot read property 'label' of undefined
```

in t
in t
in withRouter(t)
in div
in div
in t
in div
in t
in InjectIntl(t)
in Connect(InjectIntl(t))
in t
in div
in div
in i
in div
in t
in t
in InjectIntl(t)
in div
in t
in div
in t
in InjectIntl(t)
in Connect(InjectIntl(t))
in DragDropContext(Connect(InjectIntl(t)))
in t
in t
in t
in IntlProvider
in y
in Connect(y)
in r
```

**Comment by kenshyx** [comment]
This is related to #260

**Comment by SeverS** [comment]
Hello!
This is most probably from license bug we had in past and solved in a previous version.
While this can happen again with some (very old) entries, it shouldn't happen on newer ones.

Thanks for reporting!
