### ISSUE TITLE
Error code DPE01 when one tag is a number

### ISSUE THREAD

**Issue by ligi** [AkashaProject/Community#259]
![selection_046](https://user-images.githubusercontent.com/111600/39813496-fb3a269e-5390-11e8-9c07-0b587feef2bb.png)
#### System information

AKASHA version: ` 0.7.2`

Operating System: ` ubuntu 18.04`

#### Expected behaviour

should either publish a tag with only a number or not allow me to have this - but not fail with a obscure error message.

#### Actual behaviour

![selection_046](https://user-images.githubusercontent.com/111600/39813539-21bcb106-5391-11e8-897d-4314269a5630.png)

#### Steps to reproduce the problem

I could reproduce the problem when - here the tag that is only a number seems to be the problem. Removing this tag -> I could publish - making another post with only this tag -> could not publish - all *indicators* that this might be the problem.

**Comment by RMBLRX** [comment]
I noted this in #186 and would like to clarify that this only seems to occur when creating a tag with numbers, as I earlier posted a link and successfully included the existent _web3.0_ tag in it.
