### ISSUE TITLE
[Web] Backspace in category/tag section goes back a page in Firefox

### ISSUE THREAD

**Issue by codeluggage** [AkashaProject/Community#267]
#### System information

AKASHA version: `?` (IFPS Version 0.28.2, MetaMask/v4.7.1 - where do I see the Akasha version on the Rinkeby testnet for https://beta.akasha.world?)

Operating System: `macOS 10.12.6`

#### Expected behaviour

Backspace removes the text.

#### Actual behaviour

Backspace goes backwards in the page history.

#### Steps to reproduce the problem

With Firefox, create a new draft on https://beta.akasha.world, add a category at the bottom and use backspace.

**Comment by SeverS** [comment]
Hello @codeluggage ,

Can you tell me which version of Firefox you're using? Just tried with **Firefox 61.0.1 (64-bit)** and i cannot reproduce!

Thanks!
SeverS

**Comment by codeluggage** [comment]
@SeverS I should have grabbed that information! Testing it again today, also on version **61.0.1 (64-bit)**, it does not have this issue. 

As I was clicking around, pressing backspace, it looks like it was an issue with loosing focus in a text area and then backspace becomes "go back one page". That seems to not move you back one page any more though - I can see a slight flicker but it stays on the draft and nothing is lost. 

Thanks for checking! Looks like this can be closed 👍
