### ISSUE TITLE
IPFS Could not be started in the web-app

### ISSUE THREAD

**Issue by ligi** [AkashaProject/Community#268]
I am a bit confused about this:

![selection_072](https://user-images.githubusercontent.com/111600/41038654-37995198-6997-11e8-980e-4344e8271ed9.png)

Usually do not use the web-app - but I think last time I tried it I did not get this error.

**Comment by SeverS** [comment]
Hey @ligi ,

I saw that you have ipfs companion installed and it's disabled or something.
That's why that error popped.
IPFS Companion is not needed anymore to run the web version.

Thank you!
SeverS

**Comment by ligi** [comment]
> IPFS Companion is not needed anymore to run the web version.

this screen should be change then:
![selection_104](https://user-images.githubusercontent.com/111600/43405540-6078845a-941a-11e8-808a-494d97e22ed9.png)

Anyway - looks like this error is not happening anymore - I want to keep the companion installed as I have other use-cases for it.

**Comment by SeverS** [comment]
Yep, changes to that screen are planned!
So, you only need Metamask extension right now.

I am closing this but feel free to re-open if you have any more issues!
Thank you,
SeverS
