### ISSUE TITLE
Mac: Profile pic blacked out

### ISSUE THREAD

**Issue by ChaceHunter** [AkashaProject/Community#27]
I uploaded a .png image with a transparent background, and the image shows up as a black box once the app is open.

The picture appeared just fine on the Profile Creation screen.

The image in question:
![akasha](https://user-images.githubusercontent.com/12126485/34315164-06f5f92e-e742-11e7-8951-fde024d66769.png)

How it appears in app:
<img width="413" alt="screen shot 2017-12-22 at 6 01 06 pm" src="https://user-images.githubusercontent.com/12126485/34315183-1f75a724-e742-11e7-8e24-6e869a4c723c.png">

**Comment by SeverS** [comment]
#313
