### ISSUE TITLE
no indication of what's happening after publication

### ISSUE THREAD

**Issue by 42piratas** [AkashaProject/Community#284]
_From @elopio on March 7, 2017 19:34_

I published my first post and nothing happened for a while, I just returned to the previous window. Then I got a red 1 on top of my picture. This is a little confusing. After I hit the publish button, the UI should explain that it will take some time for the post to actually be published, and that once it is published I will get a notification.

_Copied from original issue: AkashaProject/Alpha#85_

**Comment by SeverS** [comment]
Hello!

As a response to this suggestion, we added notifications after publishing step.
We know there are a lot to improve on this part and we are always open to new ideas :)

Thank you for your suggestion!
SeverS
