### ISSUE TITLE
hitting "enter" while editing and entry scrolls the editor down to the bottom.

### ISSUE THREAD

**Issue by 42piratas** [AkashaProject/Community#291]
_From @dragosroua on January 15, 2017 10:16_

It's a bug insomuch as it hinders the UI experience. If a post is big, it's significant. Tested on Safari on Mac.

_Copied from original issue: AkashaProject/Alpha#19_

**Comment by 42piratas** [comment]
_From @SeverS on January 15, 2017 13:18_

Hello @dragosroua and thank you for reporting this.
This is a known bug from an external library which is not in our control. It will be addressed in the next releases.

**Comment by SeverS** [comment]
This issue was addressed in a previous version.
Feel free to re-open if it happens again!
Thanks,
Sever
