### ISSUE TITLE
cannot save details when registering new profile

### ISSUE THREAD

**Issue by efx** [AkashaProject/Community#303]
#### System information

AKASHA version: `beta ` Firefox 59.0.2

Operating System: ` `

#### Expected behaviour
I expect to be able to register a new profile when accessing the Akasha beta via metamask + companion

#### Actual behaviour

Clicking 'register profile' throws a JavaScript error
#### Steps to reproduce the problem
1. sign up for new account
2. access akasha via https://beta.akasha.world/
3. edit my profile
4. fill in details
4. click 'Register Profile' and see following errors
![screenshot from 2018-06-13 20-36-08](https://user-images.githubusercontent.com/472721/41385558-5bc3f95c-6f4a-11e8-9e54-e0dd5ec5d0ef.png)

**Comment by SeverS** [comment]
Hello @efx,

I cannot reproduce this issue (using Firefox 62). Feel free to re-open it if you still have this problem.

Thank you,
Sever
