### ISSUE TITLE
Blank page when visiting beta.akasha.world

### ISSUE THREAD

**Issue by deiu** [AkashaProject/Community#306]
#### System information

AKASHA version: `n/a `

Operating System: ` macOS High Sierra (10.13.5 )`
Browser: `Chrome 67 / Firefox 61 / Safari 11.1.1`

#### Expected behaviour
See a Web page or Web application (or any HTML rendering).

#### Actual behaviour
Blank page.

#### Steps to reproduce the problem
Opening https://beta.akasha.world/ in Chrome/Firefox/Safari does not display anything. The following messages are logged to the browser console -- https://imgur.com/a/F6WNg80.

**Comment by SeverS** [comment]
Hey @deiu!

You need to install MetaMask (Chrome/Firefox) extension, and set it to Rinkeby test network.
However there should be a page asking you to do that.
We'll check this ASAP.

Thanks for reporting!

**Comment by deiu** [comment]
I have MM installed and unlocked, but it wasn't set to use Rinkeby. There should be a welcome page that instructs people on how to deal with dependencies. :)
