### ISSUE TITLE
Unable to synchronize

### ISSUE THREAD

**Issue by AlexLesnevsky** [AkashaProject/Community#308]
#### System information

AKASHA version: ` 0.7.2`

Operating System: `Windows 10 `

#### Steps to reproduce the problem Start Akasha...
![2018-07-19_0931](https://user-images.githubusercontent.com/18067373/42925495-109c72de-8b37-11e8-9f22-3ff4333b15c9.png)

**Comment by SeverS** [comment]
This happens probably because your clock is a little off.. Try to re-synchronize it using 'Internet time'

Thank you!
SeverS
