### ISSUE TITLE
Error code PFE02 An error occurred while requesting funds from faucet

### ISSUE THREAD

**Issue by heiterwelt** [AkashaProject/Community#323]
#### System information

AKASHA version: ` 0.7.2`    
Operating System: ` macos . 10.13.6 `    
Web Browser (if applicable): ` `   

#### Expected behaviour
tap follow ,and get some test ethers, should back some test ethers.

#### Actual behaviour
show Error code PFE02 An error occurred while requesting funds from faucet

#### Steps to reproduce the problem
<img width="909" alt="2018-11-16 11 35 32" src="https://user-images.githubusercontent.com/13182705/48596381-c33fc200-e993-11e8-9d44-26b348c14c84.png">

**Please, add screenshots!**

**Comment by kenshyx** [comment]
Thank you for noticing us that the faucet was not functional! Now it should work as expected, feel free to reopen this issue if its still not working.

**Comment by heiterwelt** [comment]
it still not working

**Comment by CPCer** [comment]
@kenshyx Still shows this problem
![2018-11-28](https://user-images.githubusercontent.com/8787958/49128251-6f26cd00-f305-11e8-94c9-cd2b15631b7a.png)
