### ISSUE TITLE
Web app not serving.

### ISSUE THREAD

**Issue by sheldrake** [AkashaProject/Community#328]
#### System information

AKASHA version: `web app`    
Operating System: `Mac OS 10.14.2`    
Web Browser (if applicable): `Firefox 65b`   

#### Expected behaviour
Expected the web app to serve

#### Actual behaviour
Nothing serves. Blank page

#### Steps to reproduce the problem
Just visiting https://beta.akasha.world/

**Please, add screenshots!**
![screenshot 2019-01-15 at 10 05 45](https://user-images.githubusercontent.com/208643/51173687-db599200-18ad-11e9-89ac-4db66614eb85.png)

**Comment by kenshyx** [comment]
Sometimes the metamask extension hangs and you get a white page. Try to disable and re-enable the extension

**Comment by sheldrake** [comment]
It appears @kenshyx that you are right first time. Not unusual I understand ;-)

Cheers.
