### ISSUE TITLE
Synchronization blocked at 3660662

### ISSUE THREAD

**Issue by JMCoquoz** [AkashaProject/Community#329]
#### System information

AKASHA version: 0.7.2 
Operating System: MacOS 10.14.2  
Web Browser (if applicable): Chrome  

#### Expected behaviour
Synchronization with the peers

#### Actual behaviour
Since a few days, she remains stuck at 3660662,
Hard fork constantinople on Rinkeby?
The web version with Chrome is also more unstable.

#### Steps to reproduce the problem
No idea.

**Please, add screenshots!**
<img width="1680" alt="capture d ecran 2019-01-16 a 20 07 52" src="https://user-images.githubusercontent.com/46758847/51274699-1eac2180-19d0-11e9-9804-5613d50f897e.png">

**Comment by JMCoquoz** [comment]
alid gas used (remote: 1496942 local: 1530542) ############################## WARN [01-16|21:33:18] Synchronisation failed, dropping peer peer=343149e4feefa15d err="retrieved hash chain is invalid"

INFO
21:33:18
ERROR[01-16|21:33:18] ########## BAD BLOCK ######### Chain config: {ChainID: 4 Homestead: 1 DAO: <nil> DAOSupport: true EIP150: 2 EIP155: 3 EIP158: 3 Byzantium: 1035301 Constantinople: <nil> Engine: clique} Number: 3660663 Hash: 0x366d4e07668df795c2d252baa43d929f64bcbddd548266bfef3b931b95c69e9f &{[] 0 26167

**Comment by kenshyx** [comment]
Unfortunately until we release a new version for desktop, the AKASHA application will work only from browser :(

**Comment by JMCoquoz** [comment]
Ok, thanks for informations.
