### ISSUE TITLE
CONTRIBUTING link in README.MD is invalid

### ISSUE THREAD

**Issue by bstro** [AkashaProject/Community#331]
#### System information

AKASHA version: `N/A`
Operating System: `N/A`    
Web Browser (if applicable): ` `   

#### Expected behaviour
The link to `CONTRIBUTING` in this repo should link to a valid document

#### Actual behaviour
It doesn't :)

**Comment by 42piratas** [comment]
Hi @bstro! I'm sorry for the long delay.

We've updated the readme file and removed the reference to the old contributing file. Atm, we're going through a big revamp and soon we'll be able to share more details about the new version of the application. If you like to learn more, stay tuned to our [blog](https://akasha.org/blog).

And btw, we appreciate your interesting in contributing :-)

Cheers!
