### ISSUE TITLE
Feature request: Have a board/column for followed accounts

### ISSUE THREAD

**Issue by karalabe** [AkashaProject/Community#51]
Apparently there's no easy way to see all the posts my followed accounts have posted. Not sure if this is a design decision or something you haven't gotten to yet, but I think people kind of expect an easily reachable place to see what people I follow posted.

**Comment by karalabe** [comment]
Yes, I know I can create a new column in a board and add one (or more?) users, but I'd still like to have one listing everything (perhaps with a possibility to silence some).

**Comment by kenshyx** [comment]
There is a type o column `following feed` but right now there is no option to silence someone from your list.

**Comment by karalabe** [comment]
Aaaaah, indeed. Perhaps a more friendly name? Though I do see some posts from akashacomms, I don't see the 2 posts from you. Perhaps they don't show up because there's no peer to pull them from?

**Comment by karalabe** [comment]
Ok, definitely something's wrong. Now I can see **your** 2 posts (with no peers found), but cannot see the posts from akashacomms that I could see previously.
