### ISSUE TITLE
Build contains test data

### ISSUE THREAD

**Issue by karalabe** [AkashaProject/Community#59]
I haven't checked all the different builds, but the Linux zip one has a file called `resources/app.asar`. I'm assuming this is the main Akasha JavaScript implementation. Looking at the size, it's a bit surprising, weighing about 81MB.

Checking the content is even funkier: it contains the entire poem "Paradise Lost", along with a few thousand URLs. After some digging around, it turned out that these are the test datasets for Google's Snappy encoding (http://code.metager.de/source/xref/google/snappy/testdata/plrabn12.txt and http://code.metager.de/source/xref/google/snappy/testdata/urls.10K).

Seems a bit wasteful to include test data in a final shipped binary. Heck, it seems a bit wasteful to include these anywhere, as I don't really see who would ever want to see these out of a repository developer checkout.

**Comment by kenshyx** [comment]
These files are from https://github.com/level/leveldown. We can't remove them manually since it would break the package integrity when building.
